### ISSUE TITLE
class IInMemoryCoachRepository

### ISSUE THREAD

**Issue by trair18** [Fargus811/Competition#2] opened 2019-11-18 18:59 UTC
change name of field(try to use Shift+F6)

**Comment by trair18** [comment] 2019-11-18 19:01
`@Override
    public Coach findById(int id) {
        Coach fake = new Coach();
        fake.setId(id);
        int index = coachList.indexOf(fake);
        return sportsmanList.get(index);
    }`

understand why this code doesn't work in current version

**Comment by Fargus811** [comment] 2019-11-19 19:11
Have done

**Comment by trair18** [comment] 2019-11-19 20:01
change fields and methods order(fields should be first) and also intervals, ctrl + L

**Comment by Fargus811** [comment] 2019-11-26 20:01
I will try

**Comment by VladOsipov** [comment] 2019-11-29 10:27
Closed as a duplicate of https://github.com/Fargus811/Competition/issues/14#issue-530270014

**Closed as completed by VladOsipov** 2019-11-29 10:27 UTC
