### ISSUE TITLE
class Couch

### ISSUE THREAD

**Issue by trair18** [Fargus811/Competition#1] opened 2019-11-18 18:57 UTC
add getters and setters, hashcode, equals, tostring

**Comment by Fargus811** [comment] 2019-11-19 19:10
check out new version

**Comment by trair18** [comment] 2019-11-19 19:58
ctrl + L and same intervals between methods

**Comment by VladOsipov** [comment] 2019-11-29 10:27
Close as duplicate of https://github.com/Fargus811/Competition/issues/14#issue-530270014

**Closed as completed by VladOsipov** 2019-11-29 10:27 UTC
